'''
NOMBRE CICLO FORMATIVO: DESARROLLO DE APLICACIONES MULTIPLATAFORMA
NOMBRE MÓDULO: SISTEMAS DE GESTIÓN EMPRESARIAL
CURSO ACTUAL: 2ºDAM
NOMBRE ALUMNO: EDURDO DOMINGUEZ TORIBIO
'''
#Sintáxis y variables Python
cadena:'hola'
entero:2
decimales:2.2
buleanos:true

print(cadena)